<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Bogus" Version="35.6.5" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageVersion Include="Microsoft.IdentityModel.Tokens" Version="8.23.0" />
    <PackageVersion Include="Minio" Version="7.0.0" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageVersion Include="NRedisStack" Version="1.8.0" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.17.9" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageVersion Include="StackExchange.Redis" Version="3.3.1" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0" />
    <PackageVersion Include="System.Linq.Dynamic.Core" Version="1.7.4" />
    <PackageVersion Include="Ulid" Version="1.4.1" />
  </ItemGroup>
</Project>
